# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greet_pb2 as greet__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/greet.Greeter/SayHello',
                request_serializer=greet__pb2.HelloRequest.SerializeToString,
                response_deserializer=greet__pb2.HelloReply.FromString,
                )
        self.GetListMahasiswa = channel.unary_unary(
                '/greet.Greeter/GetListMahasiswa',
                request_serializer=greet__pb2.empty.SerializeToString,
                response_deserializer=greet__pb2.ListMhs.FromString,
                )
        self.DetailMahasiswa = channel.unary_unary(
                '/greet.Greeter/DetailMahasiswa',
                request_serializer=greet__pb2.ID.SerializeToString,
                response_deserializer=greet__pb2.Mahasiswa.FromString,
                )
        self.InsertMahasiswa = channel.unary_unary(
                '/greet.Greeter/InsertMahasiswa',
                request_serializer=greet__pb2.Mahasiswa.SerializeToString,
                response_deserializer=greet__pb2.Result.FromString,
                )
        self.EditMahasiswa = channel.unary_unary(
                '/greet.Greeter/EditMahasiswa',
                request_serializer=greet__pb2.Mahasiswa.SerializeToString,
                response_deserializer=greet__pb2.Result.FromString,
                )
        self.DeleteMahasiswa = channel.unary_unary(
                '/greet.Greeter/DeleteMahasiswa',
                request_serializer=greet__pb2.ID.SerializeToString,
                response_deserializer=greet__pb2.Result.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListMahasiswa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetailMahasiswa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertMahasiswa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditMahasiswa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMahasiswa(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=greet__pb2.HelloRequest.FromString,
                    response_serializer=greet__pb2.HelloReply.SerializeToString,
            ),
            'GetListMahasiswa': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListMahasiswa,
                    request_deserializer=greet__pb2.empty.FromString,
                    response_serializer=greet__pb2.ListMhs.SerializeToString,
            ),
            'DetailMahasiswa': grpc.unary_unary_rpc_method_handler(
                    servicer.DetailMahasiswa,
                    request_deserializer=greet__pb2.ID.FromString,
                    response_serializer=greet__pb2.Mahasiswa.SerializeToString,
            ),
            'InsertMahasiswa': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertMahasiswa,
                    request_deserializer=greet__pb2.Mahasiswa.FromString,
                    response_serializer=greet__pb2.Result.SerializeToString,
            ),
            'EditMahasiswa': grpc.unary_unary_rpc_method_handler(
                    servicer.EditMahasiswa,
                    request_deserializer=greet__pb2.Mahasiswa.FromString,
                    response_serializer=greet__pb2.Result.SerializeToString,
            ),
            'DeleteMahasiswa': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMahasiswa,
                    request_deserializer=greet__pb2.ID.FromString,
                    response_serializer=greet__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greet.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/SayHello',
            greet__pb2.HelloRequest.SerializeToString,
            greet__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetListMahasiswa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/GetListMahasiswa',
            greet__pb2.empty.SerializeToString,
            greet__pb2.ListMhs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetailMahasiswa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/DetailMahasiswa',
            greet__pb2.ID.SerializeToString,
            greet__pb2.Mahasiswa.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InsertMahasiswa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/InsertMahasiswa',
            greet__pb2.Mahasiswa.SerializeToString,
            greet__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditMahasiswa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/EditMahasiswa',
            greet__pb2.Mahasiswa.SerializeToString,
            greet__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMahasiswa(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/greet.Greeter/DeleteMahasiswa',
            greet__pb2.ID.SerializeToString,
            greet__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
