# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='greet.proto',
  package='greet',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bgreet.proto\x12\x05greet\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x65mpty\"G\n\tMahasiswa\x12\x0c\n\x04nama\x18\x01 \x01(\t\x12\x0b\n\x03nim\x18\x02 \x01(\t\x12\x0c\n\x04\x61sal\x18\x03 \x01(\t\x12\x11\n\tdatebirth\x18\x04 \x01(\t\".\n\x07ListMhs\x12#\n\tmahasiswa\x18\x01 \x03(\x0b\x32\x10.greet.Mahasiswa\"\x10\n\x02ID\x12\n\n\x02id\x18\x01 \x01(\t\"\x15\n\x06Result\x12\x0b\n\x03txt\x18\x01 \x01(\t2\xbe\x02\n\x07Greeter\x12\x34\n\x08SayHello\x12\x13.greet.HelloRequest\x1a\x11.greet.HelloReply\"\x00\x12\x32\n\x10GetListMahasiswa\x12\x0c.greet.empty\x1a\x0e.greet.ListMhs\"\x00\x12\x30\n\x0f\x44\x65tailMahasiswa\x12\t.greet.ID\x1a\x10.greet.Mahasiswa\"\x00\x12\x34\n\x0fInsertMahasiswa\x12\x10.greet.Mahasiswa\x1a\r.greet.Result\"\x00\x12\x32\n\rEditMahasiswa\x12\x10.greet.Mahasiswa\x1a\r.greet.Result\"\x00\x12-\n\x0f\x44\x65leteMahasiswa\x12\t.greet.ID\x1a\r.greet.Result\"\x00\x62\x06proto3'
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='greet.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='greet.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=50,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='greet.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='greet.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=81,
)


_EMPTY = _descriptor.Descriptor(
  name='empty',
  full_name='greet.empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=90,
)


_MAHASISWA = _descriptor.Descriptor(
  name='Mahasiswa',
  full_name='greet.Mahasiswa',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nama', full_name='greet.Mahasiswa.nama', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nim', full_name='greet.Mahasiswa.nim', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asal', full_name='greet.Mahasiswa.asal', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datebirth', full_name='greet.Mahasiswa.datebirth', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=163,
)


_LISTMHS = _descriptor.Descriptor(
  name='ListMhs',
  full_name='greet.ListMhs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mahasiswa', full_name='greet.ListMhs.mahasiswa', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=211,
)


_ID = _descriptor.Descriptor(
  name='ID',
  full_name='greet.ID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='greet.ID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=229,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='greet.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='txt', full_name='greet.Result.txt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=252,
)

_LISTMHS.fields_by_name['mahasiswa'].message_type = _MAHASISWA
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Mahasiswa'] = _MAHASISWA
DESCRIPTOR.message_types_by_name['ListMhs'] = _LISTMHS
DESCRIPTOR.message_types_by_name['ID'] = _ID
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

empty = _reflection.GeneratedProtocolMessageType('empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.empty)
  })
_sym_db.RegisterMessage(empty)

Mahasiswa = _reflection.GeneratedProtocolMessageType('Mahasiswa', (_message.Message,), {
  'DESCRIPTOR' : _MAHASISWA,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Mahasiswa)
  })
_sym_db.RegisterMessage(Mahasiswa)

ListMhs = _reflection.GeneratedProtocolMessageType('ListMhs', (_message.Message,), {
  'DESCRIPTOR' : _LISTMHS,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.ListMhs)
  })
_sym_db.RegisterMessage(ListMhs)

ID = _reflection.GeneratedProtocolMessageType('ID', (_message.Message,), {
  'DESCRIPTOR' : _ID,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.ID)
  })
_sym_db.RegisterMessage(ID)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Result)
  })
_sym_db.RegisterMessage(Result)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='greet.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=255,
  serialized_end=573,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='greet.Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetListMahasiswa',
    full_name='greet.Greeter.GetListMahasiswa',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_LISTMHS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DetailMahasiswa',
    full_name='greet.Greeter.DetailMahasiswa',
    index=2,
    containing_service=None,
    input_type=_ID,
    output_type=_MAHASISWA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InsertMahasiswa',
    full_name='greet.Greeter.InsertMahasiswa',
    index=3,
    containing_service=None,
    input_type=_MAHASISWA,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EditMahasiswa',
    full_name='greet.Greeter.EditMahasiswa',
    index=4,
    containing_service=None,
    input_type=_MAHASISWA,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteMahasiswa',
    full_name='greet.Greeter.DeleteMahasiswa',
    index=5,
    containing_service=None,
    input_type=_ID,
    output_type=_RESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
